version: "3.3"
services:
  demo:
    build: .
    ports:
      - "8080:8080"
    environment:
      UNLEASH_HOST: http://unleash:4242/api
    command: 'gradle bootRun --no-daemon'
    working_dir: '/app'
    depends_on:
      - unleash
    volumes:
      - '${PWD}/:/app'
  unleash:
    image: unleashorg/unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://postgres:unleash@db/postgres
      UNLEASH_SESSION_SECRET: secret
    depends_on:
      - db
  db:
    expose:
      - "5432"
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: unleash
